name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  dockerbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create image from repository
        run: docker build -t ghcr.io/${{ github.actor }}/hass-bot .
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/hass-bot:$(date +%Y%m%d%H%M%S)
      - name: Push image to GitHub Container Registry as latest
        run: docker push ghcr.io/${{ github.actor }}/hass-bot:latest
